import type { Metadata } from "next";
import { Roboto_Mono, Roboto, Inter } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "800"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} ${inter.variable} antialiased`}
      >
        <div className="flex h-screen justify-center w-full">
          <div className="relative w-full max-w-[90rem] px-4 sm:px-8 lg:px-20 overflow-x-hidden md:overflow-x-visible">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
